[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
glam = "0.21.3"
image = "0.24.3"
log = "0.4.17"
rand = "0.8.5"
rayon = "1.5.3"
