[package]
name = "simple-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.1"
image = "0.24.4"
log = "0.4.17"
raytracing = {path = "../raytracing" }
